### ISSUE TITLE
测试报错

### ISSUE THREAD

**Issue by DanJun6737** [Huises/IERN-for-IR-Image-SR#10]
在50 IR images上测试时，遭遇报错：

Method: EDENSEUPDOWN || Scale: 4 || Degradation: BI
Traceback (most recent call last):
  File "test.py", line 153, in <module>
    main()
  File "test.py", line 84, in main
    para_save.begin_background()
  File "test.py", line 29, in begin_background
    p.start()
  File "G:\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "G:\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "G:\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "G:\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "G:\Python\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Paralle_save_img.begin_background.<locals>.bg_target'
PS G:\DJ\IERN-for-IR-Image-SR-master\IERN-for-IR-Image-SR-master> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "G:\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "G:\Python\Python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

请作者大大帮忙看一下该如何解决呢？谢谢

**Comment by Lihui-Chen** [comment]
把异步并行保存图像设为False（关闭）
