### ISSUE TITLE
x3训练

### ISSUE THREAD

**Issue by Zhenrong-Zhou** [Huises/IERN-for-IR-Image-SR#5]
你好，请问我在使用自己的数据集进行x3训练的时候报错RuntimeError: Caught RuntimeError in DataLoader worker process 0. RuntimeError: stack expects each tensor to be equal size, but got [3, 96, 96] at entry 0 and [3, 94, 96] at entry 15是什么原因吗，在进行x2和x4训练的时候一切都正常

**Comment by Lihui-Chen** [comment]
能把完整的报错信息发一下，这个报错只能说明特征的尺寸不一样没法进行 stack.

**Comment by Zhenrong-Zhou** [comment]
好的，
Epoch: [1/2000]:   0%|          | 0/234 [00:16<?, ?it/s]
Traceback (most recent call last):
  File "/home/abc/liu/IERN/train.py", line 150, in <module>
    main()
  File "/home/abc/liu/IERN/train.py", line 85, in main
    for iter, batch in enumerate(train_loader):
  File "/home/abc/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/abc/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/abc/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/abc/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/abc/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/abc/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/abc/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/abc/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/abc/anaconda3/envs/pytorch1.8.0/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 96, 96] at entry 0 and [3, 94, 96] at entry 15

**Comment by liu1216** [comment]
不好意思打扰了请问问题解决了吗我也有相似的问题

**Comment by Lihui-Chen** [comment]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/20918860/186570300-a7837c5d-6911-4975-9ce5-bea676fed4b4.png">
问题出现在上面对数据加载的时候，你们可以检查一下是否训练集里面有个图像在裁剪为patch后的尺寸大小 是94x96x3的，与其他尺寸不一样，可以在下面这句话后面打印一下每张加载图像的尺寸来检查你们训练集图像的尺寸在裁剪为patch后是否都是96x96，然后针对性修改代码，或者数据集
<img width="715" alt="image" src="https://user-images.githubusercontent.com/20918860/186570694-d693dc8b-1418-434c-b101-ecf936d9c552.png">
